version: '3.9'

services:
  nest: 
    container_name: fast_food
    build:
      context: ./
    restart: always
    ports:
      - 8080:3000
    environment:
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    container_name: fast_food_mongo
    restart: always
    ports:
      - "27019:27017"
    expose:
      - 27019