version: '3.3'
services:
  dev:
    container_name: fastFood-api-beta1-dev
    image: fastfood-api-beta-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 80:3000
      - 3001:9229
    networks:
      - fastFood-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: fastFood-API-beta1-prod
    image: fastfood-api-beta1-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 80:3000
      - 9229:9229
    networks:
      - fastFood-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /usr/database/database:/data/db
    ports:
      - 27017:27017
    networks:
      - fastFood-network
    restart: always
networks:
  fastFood-network:
    driver: bridge
